
import com.email.durgesh.Email;
import static com.sun.org.apache.xalan.internal.lib.ExsltDatetime.date;
import java.awt.print.PrinterException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Jai Deep
 */
public class lab extends javax.swing.JFrame {

    /**
     * Creates new form lab
     */
    Connection conn = null ;
    PreparedStatement pst;
    ResultSet rs;
    public lab() {
        initComponents();
        conn = userslogin.ConnecrDB();
     combobox();   
     CurrentDateTime();
     emailsender();
    }
    private void combobox(){
        try{
           String sql="select * from lablist";
           pst=conn.prepareStatement(sql);
           rs=pst.executeQuery();

 while (rs.next()) {  

     jComboBox2.addItem(rs.getString("Test"));  

 }
        
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Failed to Connect to Database","Error Connection", JOptionPane.WARNING_MESSAGE);
        }
    }
    public void CurrentDateTime() {    
  
   DateTimeFormatter dtf = DateTimeFormatter.ofPattern("dd/MM/yyyy");  
   LocalDateTime now = LocalDateTime.now();  
   date.setText(dtf.format(now));
     
  }    
     public void emailsender(){
        String recep=p_email.getText();
        
       
   try {  
        Email email=new Email("myhospitalmanagementsystem@gmail.com","vijvucfcpmymbouj");
        //from
        email.setFrom("myhospitalmanagementsystem@gmail.com", "My Hospital Management System");
        email.setSubject("INDUS DIAGNOSTIC CENTER");
        email.setContent("Dear "+p_name1.getText()+","+'\n' +"Your Blood Sample Was Collected On "+date.getText()+". You have paid RS."+jLabel5.getText()+"." +'\n'+'\n'+"Labortist."+'\n'+"My Diagnostic Centre", "text/html");
        email.setContent("Dear "+p_name1.getText()+","+'\n' +"Your Blood Sample Was Collected On "+date.getText()+". You have paid RS."+jLabel5.getText()+"." +'\n'+'\n'+"Labortist."+'\n'+"My Diagnostic Centre", "text/html");
        email.addRecipient(recep);
        
        email.send();
        
    }catch(Exception e){
        e.printStackTrace();
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        p_email = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        p_name1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        p_number = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        charges = new javax.swing.JTextField();
        reporttime = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        p_age = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        lab_table = new javax.swing.JTable();
        add_button = new javax.swing.JButton();
        preview = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Area = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LABORATORY", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Date:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 50, 20));

        date.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        date.setText("auto_date");
        jPanel2.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 140, 20));

        p_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_emailActionPerformed(evt);
            }
        });
        jPanel2.add(p_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 150, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setText("Gender:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel6.setText("Patient Name:");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel3.setText("Charges:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, 20));
        jPanel2.add(p_name1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 150, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel7.setText("Phone No:");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, -1, 20));

        p_number.setText("+92");
        p_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_numberActionPerformed(evt);
            }
        });
        jPanel2.add(p_number, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 150, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel8.setText("Age:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, 40));

        charges.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chargesActionPerformed(evt);
            }
        });
        jPanel2.add(charges, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 110, 150, 30));

        reporttime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reporttimeActionPerformed(evt);
            }
        });
        jPanel2.add(reporttime, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 190, 110, 30));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel9.setText("Report Expected:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, -1, 20));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel10.setText("Tests:");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, 40, 40));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel11.setText("E-mail:");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, -1, 20));

        p_age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                p_ageActionPerformed(evt);
            }
        });
        jPanel2.add(p_age, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, 150, 30));

        jComboBox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox2ItemStateChanged(evt);
            }
        });
        jComboBox2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox2PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jComboBox2.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jComboBox2MouseWheelMoved(evt);
            }
        });
        jComboBox2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jComboBox2MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jComboBox2MousePressed(evt);
            }
        });
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel2.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, 150, 20));

        lab_table.setBackground(new java.awt.Color(255, 255, 255));
        lab_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Test", "Charges", "Expected Time"
            }
        ));
        jScrollPane1.setViewportView(lab_table);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 490, 150));

        add_button.setText("Add");
        add_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_buttonActionPerformed(evt);
            }
        });
        jPanel2.add(add_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, 70, 30));

        preview.setText("Preview");
        preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewActionPerformed(evt);
            }
        });
        jPanel2.add(preview, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, 30));

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Female");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("Male");
        jPanel2.add(jRadioButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, -1, -1));

        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 70, 30));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 590, 440));

        Area.setColumns(20);
        Area.setRows(5);
        Area.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane2.setViewportView(Area);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 50, 370, 390));

        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 480, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("EXIT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 450, 90, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1063, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void p_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_emailActionPerformed

    private void p_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_numberActionPerformed

    private void chargesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chargesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chargesActionPerformed

    private void reporttimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reporttimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reporttimeActionPerformed

    private void p_ageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_p_ageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_p_ageActionPerformed

    private void jComboBox2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MouseClicked
 
    }//GEN-LAST:event_jComboBox2MouseClicked

    private void add_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_buttonActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model=(DefaultTableModel) lab_table.getModel();
        model.addRow(new Object[]{jComboBox2.getSelectedItem().toString(),charges.getText(),reporttime.getText()});
        
        
        charges.setText("");
    }//GEN-LAST:event_add_buttonActionPerformed

    private void jComboBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox2ItemStateChanged
        
    }//GEN-LAST:event_jComboBox2ItemStateChanged

    private void jComboBox2MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jComboBox2MouseWheelMoved
        // TODO add your handling code here:
       
       
    }//GEN-LAST:event_jComboBox2MouseWheelMoved

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:try{    
        
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox2PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox2PopupMenuWillBecomeInvisible
        // TODO add your handling code here:
       
        String tmp=(String)jComboBox2.getSelectedItem();
       String sql="select * from lablist where Test=?";
       try{
            Statement st = conn.createStatement();
        pst=conn.prepareStatement(sql);
        pst.setString(1, tmp);
        rs=pst.executeQuery();
        if(rs.next()){
        String add1= rs.getString("Rates");
        charges.setText(add1);
        String add2= rs.getString("ReportEx");
        reporttime.setText(add2);
        
        
        }
       
    }catch(Exception e){
           System.out.println(e);
    }
    }//GEN-LAST:event_jComboBox2PopupMenuWillBecomeInvisible

    private void jComboBox2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jComboBox2MousePressed
        // TODO add your handling code here:
//        try {  
//Statement st = conn.createStatement();
//
// ResultSet r=st.executeQuery("select * from lablist");
//
// while (r.next()) {  
//
//     jComboBox2.addItem(r.getString("Test"));  
//
// }


//   conn.close();
//    } catch (SQLException e) {  
//JOptionPane.showMessageDialog(null,"Failed to Connect to Database","Error Connection", JOptionPane.WARNING_MESSAGE);  
//System.exit(0);  
//}  
    }//GEN-LAST:event_jComboBox2MousePressed

    private void previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewActionPerformed
        Area.setText(Area.getText()+"Patient Name: "+p_name1.getText()+"\t"+"Age: "+p_age.getText()+"\n"+"Phone No: "+p_number.getText()+"\t"+"Email: "+p_email.getText()+"\n");
        Area.setText(Area.getText()+"========================================"+"\n");
       
        //Area.setText(Area.getText()+"==========================================="+"\n");
        DefaultTableModel model=(DefaultTableModel) lab_table.getModel();
        Area.setText(Area.getText()+"Tests"+"\t"+"Charges"+"\t"+"Report Expected"+"\n");
        for(int i=0; i<lab_table.getRowCount();i++){
            String test=lab_table.getValueAt(i,0).toString();
            String charges=lab_table.getValueAt(i,1).toString();
            String R_time=lab_table.getValueAt(i,2).toString();
            
           Area.setText(Area.getText()+test+"\t"+charges+"\t"+R_time+"\n");
        }
        double sum=0;
        for(int j=0;j<lab_table.getRowCount(); j++){
         sum=sum+Integer.parseInt(lab_table.getValueAt(j,1).toString());
        }
        String str = Double.toString(sum);
         jLabel5.setText(str);
        emailsender();
        Area.setText(Area.getText()+"========================================"+"\n");
         Area.setText(Area.getText()+"\n"+"Total:"+"\t"+sum);
         Area.setText(Area.getText()+"\n"+"\n"+"\n"+"\n"+"\n"+"\n"+"\t"+"\t"+"Indus Diagnostic Center");
         
    }//GEN-LAST:event_previewActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        try{
            
        Area.print();
        }
        catch(PrinterException ex){
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE,null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(lab.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new lab().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Area;
    private javax.swing.JButton add_button;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField charges;
    private javax.swing.JLabel date;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable lab_table;
    private javax.swing.JTextField p_age;
    private javax.swing.JTextField p_email;
    private javax.swing.JTextField p_name1;
    private javax.swing.JTextField p_number;
    private javax.swing.JButton preview;
    private javax.swing.JTextField reporttime;
    // End of variables declaration//GEN-END:variables
}
